#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin"
name = "Jellyfin"
description.en = "Media System that manage and stream your media"
description.fr = "Système multimédia qui gère et diffuse vos médias"

version = "10.10.1~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-2.0-only"
website = "https://jellyfin.org"
demo = "https://demo.jellyfin.org/stable/web/index.html"
userdoc = "https://jellyfin.org/docs/"
code = "https://github.com/jellyfin/jellyfin"
cpe = "cpe:2.3:a:jellyfin:jellyfin"
fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 11.2"
architectures = ["armhf", "arm64", "amd64"]
multi_instance = false
ldap = true
sso = true
disk = "300M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin"

    [install.init_main_permission]
    help.en = "Jellyfin has its own login system, you should make it public to let external clients access it (mobile app, etc.)."
    help.fr = "Jellyfin a son propre système de connexion, vous devriez la laisser publique pour permettre la connexion de clients externes (app mobile, etc.)."
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Select an account to grant it access to Jellyfin's administration panel."
    ask.fr = "Choisissez un compte pour lui accorder l'accès au tableau de bord d'administration de Jellyfin."
    help.en = "You can grant this access to other accounts and groups with the permission system later."
    help.fr = "Vous pourrez octroire l'accès à d'autres comptes et groupes avec le système de permissions plus tard."
    type = "user"

    [install.discovery]
    ask.en = "Should the ports for client and server discovery be opened?"
    ask.fr = "Est-ce que les ports pour la découverte entre clients et serveur doivent être ouverts ?"
    help.en = "Enable discovery if you use Jellyfin on your local network or through a VPN to smoothen detection between clients and server. If it is installed on a VPS and only accessed via its web interface, you should disable discovery."
    help.fr = "Activez la découverte si vous utilisez Jellyfin sur votre réseau local ou via un VPN pour simplifier la détection entre clients et serveur. S'il est installé sur un VPS et utilisé uniquement via son interface web, vous devriez désactiver la découverte."
    type = "boolean"
    default = true

[resources]

    [resources.sources.server_bullseye]
    armhf.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/armhf/jellyfin-server_10.10.1+deb11_armhf.deb"
    armhf.sha256 = "b79c6af39d48c63ea81b2026585d0e45b4e5e62b34e21a21f8c2f56d805b39d5"
    arm64.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/arm64/jellyfin-server_10.10.1+deb11_arm64.deb"
    arm64.sha256 = "3dbe24427fe0acd32c7a46da108b0a826f89299e3a2e35678aca24a8d591e3c2"
    amd64.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/amd64/jellyfin-server_10.10.1+deb11_amd64.deb"
    amd64.sha256 = "aa353663ebb0e05004c8e7df0d1fe0e64984ce7b3c52bb974143fa2b574ecd4f"

    format = "whatever"
    extract = false
    rename = "jellyfin-server.deb"
    prefetch = false

    [resources.sources.server_archive_bullseye]
    armhf.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/armhf/jellyfin-server_10.10.1+deb11_armhf.deb"
    armhf.sha256 = "b79c6af39d48c63ea81b2026585d0e45b4e5e62b34e21a21f8c2f56d805b39d5"
    arm64.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/arm64/jellyfin-server_10.10.1+deb11_arm64.deb"
    arm64.sha256 = "3dbe24427fe0acd32c7a46da108b0a826f89299e3a2e35678aca24a8d591e3c2"
    amd64.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/amd64/jellyfin-server_10.10.1+deb11_amd64.deb"
    amd64.sha256 = "aa353663ebb0e05004c8e7df0d1fe0e64984ce7b3c52bb974143fa2b574ecd4f"

    format = "whatever"
    extract = false
    rename = "jellyfin-server.deb"
    prefetch = false

    [resources.sources.server_bookworm]
    armhf.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/armhf/jellyfin-server_10.10.1+deb12_armhf.deb"
    armhf.sha256 = "39bc8e08cd5067b1f2bab6a0fa32897535c74bdeb41307545e5d6bb14f380e2b"
    arm64.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/arm64/jellyfin-server_10.10.1+deb12_arm64.deb"
    arm64.sha256 = "675e336ca4712129a4fee09330127d385e65c46de87bc86f02cedcd80bbaa739"
    amd64.url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/amd64/jellyfin-server_10.10.1+deb12_amd64.deb"
    amd64.sha256 = "73fd105f3890daf7b44a3e3aeb8bd287fe1cf1bcb6d0b8924f65e7ddc6439b68"

    format = "whatever"
    extract = false
    rename = "jellyfin-server.deb"
    prefetch = false

    [resources.sources.server_archive_bookworm]
    armhf.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/armhf/jellyfin-server_10.10.1+deb12_armhf.deb"
    armhf.sha256 = "39bc8e08cd5067b1f2bab6a0fa32897535c74bdeb41307545e5d6bb14f380e2b"
    arm64.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/arm64/jellyfin-server_10.10.1+deb12_arm64.deb"
    arm64.sha256 = "675e336ca4712129a4fee09330127d385e65c46de87bc86f02cedcd80bbaa739"
    amd64.url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/amd64/jellyfin-server_10.10.1+deb12_amd64.deb"
    amd64.sha256 = "73fd105f3890daf7b44a3e3aeb8bd287fe1cf1bcb6d0b8924f65e7ddc6439b68"

    format = "whatever"
    extract = false
    rename = "jellyfin-server.deb"
    prefetch = false

    [resources.sources.web_bullseye]
    url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/amd64/jellyfin-web_10.10.1+deb11_all.deb"
    sha256 = "a4a6282dcc7a19de3b2ea5034e4ebf02e8d6a76873e272e55b0f7d1b3159b9f8"

    format = "whatever"
    extract = false
    rename = "jellyfin-web.deb"
    prefetch = false

    [resources.sources.web_archive_bullseye]
    url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/amd64/jellyfin-web_10.10.1+deb11_all.deb"
    sha256 = "a4a6282dcc7a19de3b2ea5034e4ebf02e8d6a76873e272e55b0f7d1b3159b9f8"

    format = "whatever"
    extract = false
    rename = "jellyfin-web.deb"
    prefetch = false

    [resources.sources.web_bookworm]
    url = "https://repo.jellyfin.org/files/server/debian/stable/v10.10.1/amd64/jellyfin-web_10.10.1+deb12_all.deb"
    sha256 = "71dfb78230fe1488fc7bcc28857c74ae6ef4d971cb48a2daade7c0946688c19a"

    format = "whatever"
    extract = false
    rename = "jellyfin-web.deb"
    prefetch = false

    [resources.sources.web_archive_bookworm]
    url = "https://repo.jellyfin.org/archive/server/debian/stable/v10.10.1/amd64/jellyfin-web_10.10.1+deb12_all.deb"
    sha256 = "71dfb78230fe1488fc7bcc28857c74ae6ef4d971cb48a2daade7c0946688c19a"

    format = "whatever"
    extract = false
    rename = "jellyfin-web.deb"
    prefetch = false

    [resources.sources.ffmpeg_bullseye]
    armhf.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/armhf/jellyfin-ffmpeg7_7.0.2-5-bullseye_armhf.deb"
    armhf.sha256 = "94537c71322b1cf091369ee7c0a749f6c79d29533fceb55a9cbaea2b5d55ad25"
    arm64.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/arm64/jellyfin-ffmpeg7_7.0.2-5-bullseye_arm64.deb"
    arm64.sha256 = "e4449a8a2118ef0a6f3caf51d0b34338fb1d365b9edc9863116b0eadeb478818"
    amd64.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/amd64/jellyfin-ffmpeg7_7.0.2-5-bullseye_amd64.deb"
    amd64.sha256 = "664d05d535485086af32a1bcf8e96c7cf61f25ec5d1869220655c5b44e983ffe"

    format = "whatever"
    extract = false
    rename = "jellyfin-ffmpeg7.deb"

    [resources.sources.ffmpeg_bookworm]
    armhf.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/armhf/jellyfin-ffmpeg7_7.0.2-5-bookworm_armhf.deb"
    armhf.sha256 = "be1f5b7616a0e1e0366f16014dca02b844cd4e63382e1275b800fa066d3074a9"
    arm64.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/arm64/jellyfin-ffmpeg7_7.0.2-5-bookworm_arm64.deb"
    arm64.sha256 = "ae25cf837098151f849c50bb8672d097cf4c81e47fb38bdb4ab7c41c8fcd3f75"
    amd64.url = "https://repo.jellyfin.org/files/ffmpeg/debian/7.x/7.0.2-5/amd64/jellyfin-ffmpeg7_7.0.2-5-bookworm_amd64.deb"
    amd64.sha256 = "3bc5a4f92a751c0d0acd81ed678440504eaaed60ebb3b8884e1ccb3307ec68d8"

    format = "whatever"
    extract = false
    rename = "jellyfin-ffmpeg7.deb"


    [resources.sources.plugin_ldap]
    url = "https://repo.jellyfin.org/files/plugin/ldap-authentication/ldap-authentication_19.0.0.0.zip"
    sha256 = "3b8366f670484c9ab1ece826667754b69736d910d9ccde90c105a67ba441ead9"
    in_subdir = false


    [resources.system_user]
    home = "/var/lib/jellyfin"

    [resources.install_dir]
    dir = "/var/lib/jellyfin"

    [resources.permissions]
    # auth_header=false is because Jellyfin expects custom data in the Authorization HTTP header (notably, for Jellyfin Vue)
    main.url = "/"
    main.auth_header = false

    admin.protected = true
    admin.auth_header = false
    admin.show_tile = false

    [resources.ports]
    main.default = 8095
    # If we ever want to automatically expose the discovery ports without a setting
    # servicediscovery.default = 1900
    # servicediscovery.exposed = "UDP"
    # servicediscovery.fixed = true
    # clientdiscovery.default = 7359
    # clientdiscovery.exposed = "UDP"
    # clientdiscovery.fixed = true

    [resources.apt]
